spring:
  redis:
    host: 118.31.20.148
    port: 6378
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.31.20.148:3306/everest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true